#!/usr/bin/env python3
"""
Generate others/link/linker_defs.icf for IAR EWW from a Bao platform
header (plat.h).

Mirrors the approach used in bao-hypervisor-osyx/scripts/gen_defs.py but
targets the simpler baremetal-guest platform header rather than a C struct
description file.

Usage (no-args — auto-discovers plat.h for the default platform):
    python scripts/gen_plat_defs.py

Explicit:
    python scripts/gen_plat_defs.py \\
        --platform-h src/platform/rh850-u2a16/inc/plat.h \\
        --output     others/link/linker_defs.icf

The rh850-u2a16.icf linker script includes the generated file and maps
the PLAT_* symbols to the RO_MEM_BASE / RW_MEM_BASE names used internally.
"""

import re
import sys
import argparse
from pathlib import Path

# ---------------------------------------------------------------------------
# Platform symbols extracted from plat.h
# ---------------------------------------------------------------------------

_PLAT_SYMS = (
    'PLAT_RO_MEM_BASE',
    'PLAT_RO_MEM_SIZE',
    'PLAT_RW_MEM_BASE',
    'PLAT_RW_MEM_SIZE',
    'PLAT_STACKHEAP_SIZE',
)

_DEFAULT_PLATFORM = 'rh850-u2a16'
_DEFAULT_OUTPUT   = 'others/link/linker_defs.icf'

# ---------------------------------------------------------------------------
# C header parsing
# ---------------------------------------------------------------------------

def _strip_comments(src: str) -> str:
    src = re.sub(r'/\*.*?\*/', ' ', src, flags=re.DOTALL)
    src = re.sub(r'//[^\n]*', '', src)
    return src


def _parse_int(token: str) -> int:
    t = token.strip().rstrip('UuLlSs')
    if t.lower().startswith('0x'):
        return int(t, 16)
    return int(t, 10)


def extract_defines(header_text: str, syms: tuple) -> dict:
    """
    Extract #define integer values from a C header.
    Handles both bare and parenthesised forms:
      #define SYM  0xVALUE
      #define SYM  (0xVALUE)
      #define SYM  (0xVALUEUL)
    """
    text = _strip_comments(header_text)
    result = {}
    for sym in syms:
        pattern = re.compile(
            r'#\s*define\s+' + re.escape(sym) +
            r'\s+\(?\s*(0[xX][0-9a-fA-F]+[UuLlSs]*|[0-9]+[UuLlSs]*)\s*\)?'
        )
        m = pattern.search(text)
        if m:
            result[sym] = _parse_int(m.group(1))
    return result

# ---------------------------------------------------------------------------
# ICF generation
# ---------------------------------------------------------------------------

_HEADER = '/* Generated by scripts/gen_plat_defs.py — do not edit manually */'


def generate_icf(defs: dict) -> str:
    lines = [_HEADER, '']
    for sym in _PLAT_SYMS:
        if sym in defs:
            lines.append(f'define symbol {sym} = 0x{defs[sym]:x};')
    lines.append('')
    return '\n'.join(lines)

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _find_plat_h(repo_root: Path, platform: str) -> Path:
    candidate = repo_root / 'src' / 'platform' / platform / 'inc' / 'plat.h'
    if candidate.exists():
        return candidate
    sys.exit(
        f'Error: plat.h not found: {candidate}\n'
        f'Pass --platform-h explicitly or check --platform name.'
    )


def main():
    ap = argparse.ArgumentParser(
        description='Generate others/link/linker_defs.icf from a Bao platform header.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)
    ap.add_argument('--platform-h', default=None, metavar='FILE',
                    help='Path to plat.h (default: auto-discovered via --platform)')
    ap.add_argument('--platform', default=_DEFAULT_PLATFORM,
                    help=f'Platform name for plat.h discovery '
                         f'(default: {_DEFAULT_PLATFORM})')
    ap.add_argument('--output', default=_DEFAULT_OUTPUT,
                    help=f'ICF output path (default: {_DEFAULT_OUTPUT})')
    args = ap.parse_args()

    repo_root = Path.cwd()

    if args.platform_h:
        plat_h = Path(args.platform_h)
        if not plat_h.exists():
            sys.exit(f'Error: file not found: {plat_h}')
    else:
        plat_h = _find_plat_h(repo_root, args.platform)

    defs = extract_defines(plat_h.read_text(encoding='utf-8'), _PLAT_SYMS)

    missing = [s for s in _PLAT_SYMS if s not in defs]
    if missing:
        sys.exit(
            f'Error: the following symbols were not found in {plat_h}:\n'
            + '\n'.join(f'  {s}' for s in missing)
        )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate_icf(defs), encoding='utf-8')
    print(f'Generated: {out}  (from {plat_h})')


if __name__ == '__main__':
    main()
